// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars = {
  tutorialSidebars: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
